# Generated by Django 6.0 on 2025-12-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('nacionalidad', models.CharField(default='Salvadoreña', max_length=100)),
                ('dui', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('consulta_por', models.CharField(blank=True, max_length=255, null=True)),
                ('enfermedad_actual', models.CharField(blank=True, max_length=255, null=True)),
                ('antecedentes_personales_familiares', models.CharField(blank=True, max_length=255, null=True)),
                ('pa', models.CharField(blank=True, max_length=20, null=True)),
                ('fc', models.CharField(blank=True, max_length=20, null=True)),
                ('fr', models.CharField(blank=True, max_length=20, null=True)),
                ('fum', models.DateField(blank=True, null=True)),
                ('fpm', models.DateField(blank=True, null=True)),
                ('fpp', models.DateField(blank=True, null=True)),
                ('amenorrea_semanas', models.IntegerField(default=0)),
                ('amenorrea_dias', models.IntegerField(default=0)),
                ('tipo_ultrasonido', models.CharField(blank=True, choices=[('Obstétrico', 'Obstétrico'), ('Pélvico', 'Pélvico'), ('Abdominal', 'Abdominal'), ('Transvaginal', 'Transvaginal'), ('Renal', 'Renal'), ('Mama', 'Mama'), ('Prostático', 'Prostático')], max_length=50, null=True)),
                ('detalle_ultrasonido', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
